version: "3.7"
services:
  frontend:
    build: ./blog_frontend
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_HOST =localhost
      - VITE_PORT =8000

  backend:
    build: ./blog_rest_jpa
    restart: always
    ports:
      - 8080:8080
    environment:
     - spring.datasource.url=jdbc:postgresql://db:5432/blog
     - spring.datasource.username=postgres
     - spring.datasource.password=postgres
     - spring.jpa.show-sql=true
     - spring.jpa.hibernate.ddl-auto=update
    networks:
      fullstack_app:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    networks:
      fullstack_app:
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: postgres
networks:
  fullstack_app:







